apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: hello
      
  template:
    metadata:
      labels:
        app: hello
        tier: hello
    spec:
      containers:
        - name: hello
          image: jvegavv/hello:latest
          imagePullPolicy: Always
          ports:
          - containerPort: {{ .Values.port }}
            name: hello


---
apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello
spec:
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
  selector:
    app: hello
    tier: hello
  type: LoadBalancer